CREATE DATABASE SPORTSCHEDULE;
USE SPORTSCHEDULE;

CREATE TABLE USERS(
	FULL_NAME VARCHAR(100)
    , PASS_WORD VARCHAR(50)
    , DATEOFBIRTH VARCHAR(50)
    , USERTYPE VARCHAR(50)
    , EMAIL VARCHAR(50)
    , PRIMARY KEY(EMAIL)
)ENGINE = INNODB;

CREATE TABLE PUBLICATIONS(
	IMG VARCHAR(100)
    , DESCRIPTION VARCHAR(100)
    , EMAIL VARCHAR(50)
    , ID_PUBLI INT PRIMARY KEY AUTO_INCREMENT
)ENGINE = INNODB;

CREATE TABLE TOURNAMENT(
	TOURNAMENT_NAME VARCHAR(100)
    , AGE_RANGE INT
    , SPORT VARCHAR(50)
    , REALIZATION_DATE VARCHAR(50)
    , ID_FDBACK INT
    , ID_TORN INT PRIMARY KEY AUTO_INCREMENT
)ENGINE = INNODB;

CREATE TABLE PARTICIPATE(
	ID_TORN INT
    , EMAIL VARCHAR(50)
    , ID_PART INT PRIMARY KEY AUTO_INCREMENT
)ENGINE = INNODB;

CREATE TABLE FEEDBACK(
	COMENT VARCHAR(100)
    , RATING FLOAT
    , ID_FDBACK INT PRIMARY KEY AUTO_INCREMENT
)ENGINE = INNODB;

ALTER TABLE PUBLICATIONS
ADD CONSTRAINT FK_USUPUBLI
FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE TOURNAMENT
ADD CONSTRAINT FK_FDBACKTORN
FOREIGN KEY (ID_FDBACK) REFERENCES FEEDBACK(ID_FDBACK)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PARTICIPATE
ADD CONSTRAINT FK_PARTORN
FOREIGN KEY (ID_TORN)
REFERENCES TOURNAMENT(ID_TORN)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PARTICIPATE
ADD CONSTRAINT FK_PARTUSU
FOREIGN KEY (EMAIL)
REFERENCES USERS(EMAIL)
ON UPDATE CASCADE
ON DELETE CASCADE;

select * 
from USERS;

